"""Aggregate many stored summaries into one cross-run digest (HTML or Markdown).

Unlike ``deliver.html``, which renders a single run's results, this renders the
accumulated library from the local SQLite store, grouped by detected video type.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

from ytsum.deliver.html import _escape, _markdown_to_html


def _group_by_type(summaries: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    groups: dict[str, list[dict[str, Any]]] = {}
    for row in summaries:
        groups.setdefault(str(row.get("video_type") or "general"), []).append(row)
    return dict(sorted(groups.items(), key=lambda item: (-len(item[1]), item[0])))


def render_html(summaries: list[dict[str, Any]], *, generated_at: datetime | None = None) -> str:
    now = generated_at or datetime.now()
    groups = _group_by_type(summaries)
    badges = "".join(
        f'<span class="badge">{_escape(name)}: {len(rows)}</span>' for name, rows in groups.items()
    )
    sections = (
        "\n".join(_section(name, rows) for name, rows in groups.items())
        or '<p class="empty">No summaries stored yet.</p>'
    )
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>ytsum digest - {now:%Y-%m-%d}</title>
  <style>
    * {{ box-sizing: border-box; }}
    body {{ margin: 0; font-family: Segoe UI, system-ui, -apple-system, sans-serif;
      background: #101114; color: #e9eef4; line-height: 1.6; padding: 24px; }}
    .container {{ max-width: 960px; margin: 0 auto; }}
    header {{ border: 1px solid #2b3038; background: #181b21; border-radius: 8px;
      padding: 24px; margin-bottom: 18px; }}
    h1 {{ margin: 0 0 8px; font-size: 26px; color: #ff5a5f; }}
    h2.group {{ color: #ffbe55; border-bottom: 1px solid #2b3038; padding-bottom: 6px; }}
    .badges {{ display: flex; gap: 8px; flex-wrap: wrap; margin-top: 14px; }}
    .badge {{ background: #232833; border-radius: 6px; padding: 6px 10px; font-size: 13px; }}
    .video-card {{ background: #181b21; border: 1px solid #2b3038; border-left: 4px solid #4caf50;
      border-radius: 8px; padding: 18px; margin-bottom: 14px; }}
    .video-title {{ margin: 0 0 4px; font-size: 18px; }}
    .meta, .link {{ color: #a8b3c2; font-size: 13px; }}
    a {{ color: #78c7ff; }}
    .summary {{ margin-top: 14px; background: #111318; border-radius: 8px; padding: 16px;
      white-space: pre-wrap; }}
    .summary h4 {{ color: #ffbe55; margin: 10px 0 4px; }}
    .summary ul {{ margin: 8px 0 8px 18px; padding: 0; }}
    .summary strong {{ color: #ffe082; }}
    .empty {{ color: #a8b3c2; }}
    footer {{ color: #727b88; text-align: center; font-size: 12px; padding: 18px; }}
  </style>
</head>
<body>
  <main class="container">
    <header>
      <h1>ytsum Library Digest</h1>
      <div class="meta">{now:%Y-%m-%d %H:%M:%S} &middot; {len(summaries)} summaries</div>
      <div class="badges">{badges}</div>
    </header>
    {sections}
    <footer>Generated by ytsum</footer>
  </main>
</body>
</html>"""


def _section(name: str, rows: list[dict[str, Any]]) -> str:
    cards = "\n".join(_card(row) for row in rows)
    return f'<section><h2 class="group">{_escape(name)} ({len(rows)})</h2>\n{cards}</section>'


def _card(row: dict[str, Any]) -> str:
    title = _escape(str(row.get("title") or row.get("id") or "untitled"))
    channel = _escape(str(row.get("channel") or "unknown"))
    url = _escape(str(row.get("url") or ""))
    when = _escape(str(row.get("processed_at") or ""))
    body = _markdown_to_html(str(row.get("summary") or ""))
    return f"""<article class="video-card">
  <h3 class="video-title">{title}</h3>
  <div class="meta">{channel} &middot; {when}</div>
  <div class="link"><a href="{url}">{url}</a></div>
  <div class="summary">{body}</div>
</article>"""


def render_markdown(
    summaries: list[dict[str, Any]], *, generated_at: datetime | None = None
) -> str:
    now = generated_at or datetime.now()
    lines = [
        "# ytsum Library Digest",
        "",
        f"_{now:%Y-%m-%d %H:%M:%S} · {len(summaries)} summaries_",
        "",
    ]
    for name, rows in _group_by_type(summaries).items():
        lines.append(f"## {name} ({len(rows)})")
        lines.append("")
        for row in rows:
            title = row.get("title") or row.get("id") or "untitled"
            url = row.get("url") or ""
            lines.append(f"### [{title}]({url})")
            lines.append(f"*{row.get('channel') or 'unknown'} · {row.get('processed_at') or ''}*")
            lines.append("")
            lines.append(str(row.get("summary") or "").strip())
            lines.append("")
    if len(lines) <= 4:
        lines.append("_No summaries stored yet._")
    return "\n".join(lines).rstrip() + "\n"


def write(
    summaries: list[dict[str, Any]],
    out_path: str | Path,
    *,
    fmt: str = "html",
    generated_at: datetime | None = None,
) -> Path:
    path = Path(out_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    if fmt == "markdown":
        text = render_markdown(summaries, generated_at=generated_at)
    else:
        text = render_html(summaries, generated_at=generated_at)
    path.write_text(text, encoding="utf-8")
    return path
