from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path

from ytsum.models import SummaryResult


def write(results: list[SummaryResult], directory: Path) -> Path:
    directory.mkdir(parents=True, exist_ok=True)
    now = datetime.now()
    path = directory / f"summary_{now.strftime('%Y%m%d_%H%M%S')}.html"
    total = len(results)
    success = sum(1 for item in results if item.success)
    cards = "\n".join(_card(index, result) for index, result in enumerate(results, 1))
    page = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>YouTube Summary - {now:%Y-%m-%d}</title>
  <style>
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      font-family: Segoe UI, system-ui, -apple-system, sans-serif;
      background: #101114;
      color: #e9eef4;
      line-height: 1.6;
      padding: 24px;
    }}
    .container {{ max-width: 960px; margin: 0 auto; }}
    header {{
      border: 1px solid #2b3038;
      background: #181b21;
      border-radius: 8px;
      padding: 24px;
      margin-bottom: 18px;
    }}
    h1 {{ margin: 0 0 8px; font-size: 26px; color: #ff5a5f; }}
    .stats {{ display: flex; gap: 12px; flex-wrap: wrap; margin-top: 14px; }}
    .stat {{ background: #232833; border-radius: 6px; padding: 8px 12px; }}
    .video-card {{
      background: #181b21;
      border: 1px solid #2b3038;
      border-left: 4px solid #4caf50;
      border-radius: 8px;
      padding: 18px;
      margin-bottom: 14px;
    }}
    .video-card.error {{ border-left-color: #ff5a5f; }}
    .video-title {{ margin: 0 0 4px; font-size: 18px; }}
    .meta, .link {{ color: #a8b3c2; font-size: 13px; }}
    a {{ color: #78c7ff; }}
    .summary {{
      margin-top: 14px;
      background: #111318;
      border-radius: 8px;
      padding: 16px;
      white-space: pre-wrap;
    }}
    .summary h4 {{ color: #ffbe55; margin: 10px 0 4px; }}
    .summary ul {{ margin: 8px 0 8px 18px; padding: 0; }}
    .summary strong {{ color: #ffe082; }}
    footer {{ color: #727b88; text-align: center; font-size: 12px; padding: 18px; }}
  </style>
</head>
<body>
  <main class="container">
    <header>
      <h1>YouTube Summary Digest</h1>
      <div class="meta">{now:%Y-%m-%d %H:%M:%S}</div>
      <div class="stats">
        <div class="stat">Videos: <strong>{total}</strong></div>
        <div class="stat">Summarized: <strong>{success}/{total}</strong></div>
      </div>
    </header>
    {cards}
    <footer>Generated by ytsum</footer>
  </main>
</body>
</html>"""
    path.write_text(page, encoding="utf-8")
    return path


def _card(index: int, result: SummaryResult) -> str:
    status = "success" if result.success else "error"
    title = _escape(result.title or result.id)
    body = _markdown_to_html(result.summary if result.success else result.error_message)
    return f"""<section class="video-card {status}">
  <h2 class="video-title">{index}. {title}</h2>
  <div class="meta">{_escape(result.channel or "unknown")} | {result.video_type}</div>
  <div class="link"><a href="{_escape(result.url)}">{_escape(result.url)}</a></div>
  <div class="summary">{body}</div>
</section>"""


def _escape(text: str) -> str:
    return (
        text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")
    )


def _markdown_to_html(text: str) -> str:
    escaped = _escape(text)
    escaped = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", escaped)
    escaped = re.sub(r"^#{2,3} (.+)$", r"<h4>\1</h4>", escaped, flags=re.MULTILINE)
    escaped = re.sub(r"^- (.+)$", r"<li>\1</li>", escaped, flags=re.MULTILINE)
    escaped = re.sub(r"((?:<li>.*</li>\n?)+)", r"<ul>\1</ul>", escaped)
    return escaped
